# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

#Assignment 1.1
a = np.random.randint( 1 , 21, size=(5, 5))
a

array([[ 4,  6, 11, 10,  6],
       [ 7,  9, 13, 19,  8],
       [ 2,  6, 17,  9, 20],
       [ 2,  6,  8, 20,  4],
       [11, 11, 10, 14,  9]], dtype=int32)

In [5]:
#Assignment 1.2
b = np.random.randint( 1 , 17 , size = (4,4))
np.fill_diagonal(b , 0)
b

array([[ 0,  9, 14,  9],
       [ 9,  0, 14,  7],
       [ 8,  5,  0,  4],
       [15, 11,  9,  0]], dtype=int32)

In [9]:
#Assignment 2.1
c = np.random.randint( 1  , 17 , size=(6,6))
c

array([[ 5, 13,  8,  7,  2,  9],
       [ 7, 14, 14,  1,  6,  8],
       [13,  6,  1,  6, 14, 11],
       [11,  6,  8,  5, 10, 11],
       [ 3,  5, 14, 10, 10,  2],
       [14, 12,  8,  8,  5, 14]], dtype=int32)

In [20]:
c[2:5 , 1:5]

array([[ 6,  1,  6, 14],
       [ 6,  8,  5, 10],
       [ 5, 14, 10, 10]], dtype=int32)

In [33]:
d = np.random.randint( 100 ,size = (5,5))
d

array([[84,  3, 13, 40, 59],
       [46, 14, 12, 81,  1],
       [67, 56, 19,  9, 55],
       [96, 98, 12, 40, 29],
       [15, 92, 69, 63, 50]], dtype=int32)

In [51]:
#Assignment 2.2

d = np.random.randint(0, 100, (5, 5))
d

array([[66, 87, 90, 60, 95],
       [13, 31, 66,  9, 34],
       [37,  5, 95,  0, 94],
       [67, 91, 95, 84, 16],
       [78, 33, 93, 27, 18]], dtype=int32)

In [58]:
d_new = np.concatenate((d[ : , 0 ] , d[: , -1] , d[ 0 , :] , d[ -1 , :]) )
d_new

array([66, 13, 37, 67, 78, 95, 34, 94, 16, 18, 66, 87, 90, 60, 95, 78, 33,
       93, 27, 18], dtype=int32)

In [60]:
#Assignment 3.1
e1 = np.random.randint(100 , size=(3,4))
e1


array([[76, 16, 25, 65],
       [24, 27, 63, 99],
       [46, 29, 11, 13]], dtype=int32)

In [61]:
e2 = np.random.randint(100 , size=(3,4))
e2


array([[24, 54, 44, 57],
       [59, 27, 74, 38],
       [16,  5, 57, 68]], dtype=int32)

In [62]:
print(e1+e2)

[[100  70  69 122]
 [ 83  54 137 137]
 [ 62  34  68  81]]


In [63]:
print(e1-e2)

[[ 52 -38 -19   8]
 [-35   0 -11  61]
 [ 30  24 -46 -55]]


In [64]:
print(e1*e2)

[[1824  864 1100 3705]
 [1416  729 4662 3762]
 [ 736  145  627  884]]


In [65]:
print(e1/e2)

[[3.16666667 0.2962963  0.56818182 1.14035088]
 [0.40677966 1.         0.85135135 2.60526316]
 [2.875      5.8        0.19298246 0.19117647]]


In [67]:
#Assignment 3.2
f = np.random.randint( 1 , 17 , size=(4,4))
f

array([[ 6,  4, 14,  9],
       [14,  8, 13,  6],
       [ 9,  6,  6,  5],
       [ 2,  7, 10, 11]], dtype=int32)

In [85]:
np.sum(f , axis=1)


array([33, 41, 26, 30])

In [70]:
np.sum(f , axis =0 )

array([31, 25, 43, 31])

In [88]:
#assignment 4.1
g = np.random.randint(100 , size=(5,5))
print(g)
print( 'mean =', np.mean(g))
print(f'median = {np.median(g)}' )
print(f'std = {np.std(g):.2f}' )
print(f"vary = {np.var(g)}")


[[99 92 24 13  2]
 [28 36 36 38 42]
 [44 73 24 15  2]
 [41 61 90 74 84]
 [ 2 92 11 24 25]]
mean = 42.88
median = 36.0
std = 30.68
vary = 940.9856


In [102]:
#assignment 4.2
arr = np.arange(1, 10).reshape((3, 3))
print(arr)
print( f'mean = {np.mean(arr):.2f}')
print(f'std = {np.std(arr):.2f}' )

nomalize = (arr - np.mean(arr))/np.std(arr)
print(nomalize)
print( f'mean = {np.mean(nomalize):.2f}')
print(f'std = {np.std(nomalize):.2f}' )




[[1 2 3]
 [4 5 6]
 [7 8 9]]
mean = 5.00
std = 2.58
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
mean = 0.00
std = 1.00


In [104]:
#assignment 5.1
arr = np.random.randint( 100 , size=(3,3))
row = np.random.randint( 100 , size=(3 , ))
print(arr)
print(row)

print(arr+row)

[[25 62 97]
 [94 48 30]
 [14 95 42]]
[ 5 27 31]
[[ 30  89 128]
 [ 99  75  61]
 [ 19 122  73]]


In [128]:
#assignment 5.2
arr = np.random.randint( 100 , size=(4,4))
cols = np.random.randint( 100 , size=(4 , ))
print(arr)
print(cols)
print( arr - cols.reshape(( 4 , 1)) )



[[56 92 27 15]
 [84 97 31 25]
 [ 2 23 59  2]
 [57 44 54 91]]
[26 40 86  2]
[[ 30  66   1 -11]
 [ 44  57  -9 -15]
 [-84 -63 -27 -84]
 [ 55  42  52  89]]


In [149]:
#assignment 6.1
arr = np.random.randint(1 , 10 , size=(3,3))
print(arr)
arr_det = np.linalg.det(arr)
arr_inv = np.linalg.inv(arr)
arr_eigen = np.linalg.eigvals(arr)
print(f'detenminent = {arr_det}')
print(arr_inv)
print(arr_eigen)



[[3 6 7]
 [3 5 8]
 [3 9 8]]
detenminent = -12.0
[[ 2.66666667e+00 -1.25000000e+00 -1.08333333e+00]
 [ 7.40148683e-17 -2.50000000e-01  2.50000000e-01]
 [-1.00000000e+00  7.50000000e-01  2.50000000e-01]]
[17.76342433  0.32367647 -2.0871008 ]


In [154]:
#assignemnt 6.2
arr_1 = np.random.randint( 1, 10 , size = (2,3))
arr_2 = np.random.randint( 1, 10 , size = (3,2))
print(arr_1)
print(arr_2)
arr_mul = np.matmul(arr_1 ,arr_2)
print(arr_mul)

[[3 8 6]
 [3 4 3]]
[[4 9]
 [7 6]
 [8 9]]
[[116 129]
 [ 64  78]]


In [156]:
#assignment 7.1
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr.reshape(1,9))
print(arr.reshape(9,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [159]:
#assignment 7.2
arr = np.random.randint( 1, 10 , size = (5,5))
print(arr)
arr_new = arr.flatten()
print(arr_new)
arr_new = arr.reshape(5,5)
print(arr_new)



[[7 8 6 4 4]
 [1 2 2 3 6]
 [5 6 6 6 2]
 [2 5 2 1 5]
 [6 9 2 5 1]]
[7 8 6 4 4 1 2 2 3 6 5 6 6 6 2 2 5 2 1 5 6 9 2 5 1]
[[7 8 6 4 4]
 [1 2 2 3 6]
 [5 6 6 6 2]
 [2 5 2 1 5]
 [6 9 2 5 1]]


In [168]:
#assignment 8.1
arr = np.random.randint( 1, 10 , size = (5,5))
print(arr)
cornor = arr[ [ 0 , 0 , -1 , -1] ,  [0, -1, 0, -1] ]
print(cornor)


[[7 1 5 2 1]
 [4 1 1 5 8]
 [9 5 7 5 5]
 [7 9 6 3 3]
 [9 3 6 2 5]]
[7 1 9 5]


In [172]:
#assignment 8.2
arr = np.random.randint( 20 , size = (4,4))
print(arr)
arr[ arr > 10 ] = 10
print(arr)



[[ 8 16  1 12]
 [14  0 12  0]
 [14  3  0  6]
 [15  3 14  5]]
[[ 8 10  1 10]
 [10  0 10  0]
 [10  3  0  6]
 [10  3 10  5]]


In [176]:
#assignment 9.1
type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('A', 25, 62.2), ('B', 15, 21.3), ('C', 80, 45.2)], dtype=type)
print(data)
print(np.sort(data,order= 'age'))



[('A', 25, 62.2) ('B', 15, 21.3) ('C', 80, 45.2)]
[('B', 15, 21.3) ('A', 25, 62.2) ('C', 80, 45.2)]


In [179]:
#assignment 9.2
import math 
type = [ ('x','f4') , ('y' , 'f4')]
data = np.array([(1,1) , (2,2) , (3,3) ] , dtype=type)
print(data)

np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)

[(1., 1.) (2., 2.) (3., 3.)]


array([[0.       , 1.4142135, 2.828427 ],
       [1.4142135, 0.       , 1.4142135],
       [2.828427 , 1.4142135, 0.       ]], dtype=float32)

In [ ]:
import numpy.ma as ma
#assignment 10.1
arr = np.random.randint(1, 20, size=(4, 4))
print(arr)
print(ma.masked_greater(arr , 10))


[[18  4  8 19]
 [12  4 10  2]
 [13 18 16  1]
 [ 4  5 10 13]]
[[-- 4 8 --]
 [-- 4 10 2]
 [-- -- -- 1]
 [4 5 10 --]]


In [185]:
#assignment 10.2
arr = np.random.randint(1, 20, size=(3, 3))
print(arr)
arr_mask = ma.masked_array(arr , np.eye(3))
print(arr_mask)

mean_mask = np.mean(arr_mask)
print(arr_mask.filled(mean_mask))

[[ 9 10 10]
 [15 12  1]
 [10 12  7]]
[[-- 10 10]
 [15 -- 1]
 [10 12 --]]
[[ 9 10 10]
 [15  9  1]
 [10 12  9]]
